# Site settings
title: 一叶空间
subtitle: 一花一世界 一叶一清凉
email: mickyching@gmail.com
description:
  一花一世界 一叶一清凉

baseurl: ""
url: "http://yemic.com"
host: localhost
port: 4001

github_username: mickyching

permalink: /:categories/:title.html
paginate: 7
paginate_path: "page/:num"
gems: [jekyll-paginate]

defaults:
  -
    values:
      layout: "post"
      author: 敬叶
